### ISSUE TITLE
Idea: Convert this to a Yo generator

### ISSUE THREAD

**Issue by amitaibu** [zero2one/drupal7-skeleton#14]
The problem with the existing project is that your typical flow is:
1. Clone project
2. `./initnewprofile`
3. Remove `.git` folder and only then `git init`

By making this  a Yo generator, one could scaffold with more ease the profile and avoid the first 3 steps.

**Comment by zero2one** [comment]
Everybody with a *nix system (mac & linux) has already a bash environment. 
Not everybody has Yeoman installed...

You can also:
1. Download project
2. `./initnewprofile`
3. Put in whatever version system

**Comment by amitaibu** [comment]
np, just a suggestion :)
