### ISSUE TITLE
Add option to install without building

### ISSUE THREAD

**Issue by amitaibu** [zero2one/drupal7-skeleton#17]
sometimes we would like to quickly install the profile without needing to re-download the modules. 

Maybe `./install --no-build`?

**Comment by zero2one** [comment]
```
./scripts/reset 
```
- This will wipe the sites/default/files directory
- This will remove the settings.php directory
- This will run the drupal installer with the profile

You can use the same options as during install:
- -d : import dummy data
- -l : auto login after reset
- -y : confirm all questions 

Note to myself: update documentation…

**Comment by amitaibu** [comment]
right, I forgot I saw it there. 10x :)
